[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "latest"

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # optional, deploy the lighthouse report to a path under your site
  [plugins.inputs.audits]
    output_path = "reports/lighthouse.html"